hierarchy/about/urls.py
from django.urls import path
from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.aboutauthorview, name='author'),
]

hierarchy/folder_hierarchy/urls.py
from django.urls import path
from . import views

# app_name = 'folder_hierarchy'

urlpatterns = [
    path('', views.index, name='index'),
    path('course-content/', views.сourse_content, name='course_content'),
    path('<str:slug>/', views.group_posts, name='post-by-category'),
]

hierarchy/hierarchy/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('folder_hierarchy.urls')),
    path('about/', include('about.urls', namespace='about')),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
]

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

hierarchy/users/urls.py
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordChangeView,
    PasswordChangeDoneView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,)

from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
    path(
        'logout/',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'
    ),
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),
    path(
        'password_change/',
        PasswordChangeView.as_view(
            template_name='users/password_change_form.html'
        ),
        name='password_change'
    ),
    path(
        'password_change/done/',
        PasswordChangeDoneView.as_view(
            template_name='users/password_change_done.html'
        ),
        name='password_change_done'
    ),
    path(
        'password_reset/',
        PasswordResetView.as_view(
            template_name='users/password_reset_form.html'
        ),
        name='password_reset_form'
    ),
    path(
        'password_reset/done/',
        PasswordResetDoneView.as_view(
            template_name='users/password_reset_done.html'
        ),
        name='password_reset_done'
    ),
    path(
        'reset/<uidb64>/<token>/',
        PasswordResetConfirmView.as_view(
            template_name='users/password_reset_confirm.html'
        ),
        name='password_reset_confirm'
    ),
    path(
        'reset/done/',
        PasswordResetCompleteView.as_view(
            template_name='users/password_reset_complete.html'
        ),
        name='password_reset_complete'
    ),
]

hierarchy/about/models.py
# from django.db import models

# Create your models here.

hierarchy/folder_hierarchy/models.py
from django.db import models
from django.urls import reverse
from mptt.models import MPTTModel, TreeForeignKey


class Post(models.Model):
    serial_number = models.TextField(
        max_length=5,
        blank=True,
        verbose_name='№п/п',
    )
    category = TreeForeignKey(
      'Category', on_delete=models.PROTECT,
      related_name='posts',
      verbose_name='Название папки'
    )
    title = models.CharField(
        max_length=100,
        verbose_name='Название видео'
    )
    content = models.TextField(verbose_name='Текст над видео', blank=True)
    link_text = models.TextField(verbose_name='Ссылка на ютуб', blank=True)
    book = models.FileField(
        verbose_name='PDF-файл',
        upload_to='books/',
        blank=True
    )
    name_book = models.TextField(
        verbose_name='Текст PDF-кнопки',
        blank=True,
        max_length=150
    )
    free_videos = models.BooleanField(
        verbose_name='Бесплатно',
        default=False
    )
    slug = models.SlugField(max_length=150)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Запись'
        verbose_name_plural = 'Записи'
        ordering = ['serial_number']


class Category(MPTTModel):
    title = models.CharField(
        max_length=50,
        unique=True,
        verbose_name='Папка'
    )
    parent = TreeForeignKey(
        'self',
        on_delete=models.PROTECT,
        null=True,
        blank=True,
        related_name='children',
        db_index=True,
        verbose_name='Родительская папка'
    )
    slug = models.SlugField()

    class MPTTMeta:
        order_insertion_by = ['title']

    class Meta:
        unique_together = [['parent', 'slug']]
        verbose_name = 'Папку'
        verbose_name_plural = 'Папки'

    def get_absolute_url(self):
        return reverse('post-by-category', args=[str(self.slug)])

    def __str__(self):
        return self.title

hierarchy/users/models.py
# from django.db import models

# Create your models here.

hierarchy/users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model


User = get_user_model()


class CreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('first_name', 'last_name', 'username', 'email')

hierarchy/about/views.py
# from django.views.generic.base import TemplateView


# class AboutAuthorView(TemplateView):
#     template_name = 'about/author.html'

from django.shortcuts import render
from folder_hierarchy.models import Category


def aboutauthorview(request):
    post_list = Category.objects.select_related().all()
    template = 'about/author.html'

    context = {
        'post_list': post_list,
    }
    return render(request, template, context)

hierarchy/core/views.py
from django.shortcuts import render


def page_not_found(request, exception):
    return render(request, 'core/404.html', {'path': request.path}, status=404)


def server_error(request):
    return render(request, 'core/500.html', status=500)


def permission_denied(request, exception):
    return render(request, 'core/403.html', status=403)


def csrf_failure(request, reason=''):
    return render(request, 'core/403csrf.html')

hierarchy/folder_hierarchy/views.py
# from django.views.generic import ListView
from django.shortcuts import render, get_object_or_404
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required

# from mptt.utils import drilldown_tree_for_node

from .models import Post, Category

User = get_user_model()


def index(request):
    post_list = Category.objects.select_related().all()
    template = 'hierarchy/category_list.html'

    context = {
        'post_list': post_list,
    }
    return render(request, template, context)


def сourse_content(request):
    post_list = Category.objects.select_related().all()
    template = 'hierarchy/сourse_content.html'

    context = {
        'post_list': post_list,
    }
    return render(request, template, context)


@login_required
def group_posts(request, slug):
    category = get_object_or_404(Category, slug=slug)
    object_list = Post.objects.filter(category=category)
    template = 'hierarchy/post_list.html'
    post_list = Category.objects.filter(parent_id=category.id)
    category_tree = Category.objects.filter(id=category.parent_id)
    up_hierarchy = category.get_ancestors(ascending=False, include_self=False)
    # print("!!!!!!!!!!!!!!!!_get_ancestors:", up_hierarchy)

    context = {
        'object_list': object_list,
        'post_list': post_list,
        'category': category,
        'category_tree': category_tree,
        'up_hierarchy': up_hierarchy,
    }
    return render(request, template, context)

hierarchy/users/views.py
from django.views.generic import CreateView

from django.urls import reverse_lazy

from .forms import CreationForm


class SignUp(CreateView):
    form_class = CreationForm
    success_url = reverse_lazy('posts:index')
    template_name = 'users/signup.html'

hierarchy/templates/about/author.html
{% extends "hierarchy/base.html" %} 
{% block title %}Об авторе{% endblock %}
{% block content %}
{% load mptt_tags %}
{% load static %}
<h1 style="text-align: center; margin-top: 55px;">Приветствую на моей страничке!</h1>
<br>

<div class="author_wrapper">

  <div class="author_wrapper_section">
    <div class="author_img_div">
      <img class="author_img" src="{% static 'img/author.JPG' %}">
    </div>

    <div class="author_text">
      <p>
        Я Анастасия Дементьева - практикующий специалист по кинезиологическому тейпированию. 
        <br>
        Рассказываю и показываю, как с помощью тейпов вернуть здоровое сияние Вашей коже, стереть мелкие морщинки и уменьшить глубокие, подтянуть овал лица, убрать отёки с лица и тела. А также устранить мышечные спазмы и зажимы, тем самым убрав причину многих болей.
      </p>
    </div>
  </div>

  <hr class="author_wrapper_hr">

  <div class="author_wrapper_section">
    <div class="author_img_div">
      <img class="author_img" src="{% static 'img/imageautor2.jpg' %}">
    </div>

    <div class="author_text">
      <p>
        Чтобы тейпирование приносило лишь пользу и радость от результата, применять этот инструмент нужно правильно. Поскольку тейпы воздействуют на мышцы, нужно знать, где нужная мышца находится. 
        А для более выраженного эффекта наши мышцы очень любят мануальные техники перед процедурой тейпирования. 
        <br>
        Важные правила и рабочие техники тейпирования и предварительного массажа я подробно описываю на своём курсе, на который Вас и приглашаю.
      </p>
    </div>
  </div>

  <hr class="author_wrapper_hr">

  <div class="author_certificates">
    <h3>Мои сертификаты</h3>
    <!-- Cекция со слайдером -->
    <section class="caruosel">
      <div class="conteiner">
        <div class="caruosel__inner">
          <div>
            <a href="{% static 'img/certificat1.jpg' %}" class="caruosel__inner_link">
              <img src="{% static 'img/certificat1.jpg' %}" alt="1">
            </a>
          </div>
          <div>
            <a href="{% static 'img/certificat2.PNG' %}" class="caruosel__inner_link">
              <img src="{% static 'img/certificat2.PNG' %}" alt="2">
            </a>
          </div>
          <div>
            <a href="{% static 'img/certificat3.PNG' %}" class="caruosel__inner_link">
              <img src="{% static 'img/certificat3.PNG' %}" alt="3">
            </a>
          </div>
          <div>
            <a href="{% static 'img/certificat4.PNG' %}" class="caruosel__inner_link">
              <img src="{% static 'img/certificat4.PNG' %}" alt="4">
            </a>
          </div>
          <div>
            <a href="{% static 'img/certificat5.PNG' %}" class="caruosel__inner_link">
              <img src="{% static 'img/certificat5.PNG' %}" alt="5">
            </a>
          </div>
        </div>
      </div>
    </section>
  </div>
  
  <hr class="author_wrapper_hr">

  <section class="social_networks">
    <h3>Не забудь подписаться 🥰👇</h3>
    <a class="navbar-brand" target="_blank" href="https://likee.video/@ansstasia_new?af_sub4=&af_sub5=&l=ru">
      <img class="social_networks_img" src="{% static 'img/socialnetworks/likee.png' %}" width="65" height="65" class="d-inline-block align-top" alt="likee">
    </a>
    <a class="navbar-brand" target="_blank" href="https://www.youtube.com/channel/UCeiHtvZQwqonRJO_R1xmnfw">
      <img class="social_networks_img" src="{% static 'img/socialnetworks/youtube.png' %}" width="65" height="65" class="d-inline-block align-top" alt="youtube">
    </a>
    <a class="navbar-brand" target="_blank" href="https://vk.com/tape_for_you">
      <img class="social_networks_img" src="{% static 'img/socialnetworks/vk.png' %}" width="65" height="65" class="d-inline-block align-top" alt="vk">
    </a>
    <a class="navbar-brand" target="_blank" href="https://www.tiktok.com/@anastasija_dementeva?refer=creator_embed">
      <img class="social_networks_img" src="{% static 'img/socialnetworks/tiktok.png' %}" width="65" height="65" class="d-inline-block align-top" alt="tiktok">
    </a>

    <div class="author_button">
      <a class="css-button-tme" target="_blank" href="https://t.me/anastasiadementeva">
        <img class="social_networks_img" src="{% static 'img/socialnetworks/tme.png' %}" width="65" height="65" class="d-inline-block align-top" alt="tme">
        <span class="css-button-text-tme">А тут бесплатный клуб с обзорами моих уроков💝</span>
      </a>
    </div>
  </section>

  <hr class="author_wrapper_hr">

  {% if request.user.is_authenticated %}
    <div class="author_button">
      <a class="css-button-downloads" href="{% url 'index' %}">
        <span class="css-button-text-downloads">Начать обучение</span>
      </a>
    </div>

  {% else %}
    <div class="author_button">
      <a class="css-button-downloads" href="{% url 'course_content' %}">
        <span class="css-button-text-downloads">Содержание курса</span>
      </a>
    </div>
    
    {% include 'hierarchy/includes/buy_course_button.html' %}

  {% endif %}

</div>
{% endblock %} 

hierarchy/templates/core/403csrf.html
{% extends "base.html" %}
{% block title %}Custom CSRF check error{% endblock %}
{% block content %}
  <h1>Custom CSRF check error. 403</h1>
{% endblock %}

hierarchy/templates/hierarchy/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">
    <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <meta http-equiv="X-UA-Compatible" content="ie=edge"> <!-- Для совместимости с IE -->
      {% comment %} <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/fav/apple-touch-icon.png' %}"> {% endcomment %}
      <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/fav/favicon-32x32.png' %}">
      <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/fav/favicon-16x16.png' %}">
      <meta name="msapplication-TileColor" content="#000">
      <meta name="theme-color" content="#ffffff">
      <meta name="author" content="Dementev Alexandr">
      <link rel="stylesheet" href="{% static '/css/bootstrap.min.css' %}">
      <link rel="stylesheet" href="{% static '/css/custom.css' %}">

      <!-- Слайдер -->
      <script type="text/javascript" src="https://code.jquery.com/jquery-1.11.0.min.js"></script>
      <script type="text/javascript" src="{% static '/js/slick.min.js' %}"></script>
      <script type="text/javascript" src="{% static 'script.js' %}"></script>
      
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js" integrity="sha384-Atwg2Pkwv9vp0ygtn1JAojH0nYbwNJLPhwyoVbhoPwBhjQPR5VtM2+xf0Uwh9KtT" crossorigin="anonymous"></script>

      <title>{% block title %}Последние обновления на сайте{% endblock title %}</title>
      </head>
    <body>
        {% include 'includes/header.html' %}  

        <main> 
            <div class="container py-5">
              {% block content %}
                Обшибка загрузки контента. Попробуйте позже.
              {% endblock %} 
            </div> 
        </main>

        {% include 'includes/footer.html' %}

        {% comment %} <script type="text/javascript" src={% static "/js/bootstrap.bundle.min.js" %}></script>
        <script type="text/javascript" src={% static "/js/bootstrap.min.js" %}></script> {% endcomment %}
        {% comment %} <script type="text/javascript" src={% static "/js/bootstrap.esm.min.js" %}></script> {% endcomment %}
        {% comment %} <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script> {% endcomment %}
        {% comment %} <script type="text/javascript" href="{% static '/script.js' %}"></script> {% endcomment %}
    </body>
</html>

hierarchy/templates/hierarchy/category_list.html
{% extends "hierarchy/base.html" %} 
{% load mptt_tags %}

{% block title %}Список категорий{% endblock %}

{% block content %}

<div>
	{% if request.user.is_authenticated %}
		<h2 class="h2_tree">Добро пожаловать!</h2>
		{% else %}
		<h5 class="h5_tree">
			Войдите в систему, чтобы продолжить обучение.
			<br>
			Если вы ещё не приобрели курс, вы можете это сделать на странице автора.
			<div class="css-button-div">
				<a class="css-button-downloads" href="{% url 'about:author' %}">
					<span class="css-button-text-downloads">Об авторе</span>
				</a>
			</div>

		</h5>
	{% endif %}
    <div>			
			<ul class="ul_tree">
			{% recursetree post_list %}
					<li class="li_tree">
							<a class="css-button-text css-button" href="{{node.get_absolute_url}}">

								<span class="css-button-icon">
									<svg width="21" height="21" viewBox="2 2 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
										<path d="M11.828 6a3 3 0 01-2.12-.879l-.83-.828A1 1 0 008.173 4H4.5a1 1 0 00-1 .981L3.546 6h-1L2.5 5a2 2 0 012-2h3.672a2 2 0 011.414.586l.828.828A2 2 0 0011.828 5v1z"/>
										<path fill-rule="evenodd" d="M15.81 6H4.19a1 1 0 00-.996 1.09l.637 7a1 1 0 00.995.91h10.348a1 1 0 00.995-.91l.637-7A1 1 0 0015.81 6zM4.19 5a2 2 0 00-1.992 2.181l.637 7A2 2 0 004.826 16h10.348a2 2 0 001.991-1.819l.637-7A2 2 0 0015.81 5H4.19z" clip-rule="evenodd"/>
										<path d="M10.616 12.24l3.182-1.969a.442.442 0 000-.742l-3.182-1.97c-.27-.166-.616.036-.616.372V8.7c-.857 0-3.429 0-4 4.8 1.429-2.7 4-2.4 4-2.4v.769c0 .336.346.538.616.371z"/>
									</svg>
								</span>

								{{node.title}}
							</a>
						
						{% if not node.is_leaf_node %}
							{% comment %} <ul class="children {% if node.level == 1 %}class_1{% elif node.level == 2 %}class_2{% endif %}"> {% endcomment %}
							<ul class="children">
								<span class="css-button-text">{{ children }}</span>
							</ul>
						{% endif %}
					</li>
			{% endrecursetree %}
			</ul>
    </div>
</div>

{% endblock %}

hierarchy/templates/hierarchy/includes/buy_course_button.html
<div class="author_button">
  <a class="css-button-downloads" href="https://taplink.cc/anastasia_new_version">
    <span class="css-button-text-downloads">Приобрести курс</span>
  </a>
</div>

hierarchy/templates/hierarchy/сourse_content.html
{% extends "hierarchy/base.html" %} 
{% block title %}Содержание курса{% endblock %}
{% block content %}
{% load mptt_tags %}
{% load static %}
<h1 style="text-align: center; margin-top: 55px;">Содержание курса</h1>
<br>

<div class="author_wrapper">

  <ul class="ul_tree">
  {% recursetree post_list %}
      <li class="li_tree">
        <a class="css-button-text css-button">
          <span class="css-button-icon">
            <svg width="16" height="16" viewBox="2 2 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
              <path fill-rule="evenodd" d="M6.646 11.646a.5.5 0 01.708 0L10 14.293l2.646-2.647a.5.5 0 01.708.708l-3 3a.5.5 0 01-.708 0l-3-3a.5.5 0 010-.708z" clip-rule="evenodd"/>
              <path fill-rule="evenodd" d="M10 4.5a.5.5 0 01.5.5v9a.5.5 0 01-1 0V5a.5.5 0 01.5-.5z" clip-rule="evenodd"/>
            </svg>
          </span>

          {{node.title}}
        </a>

        <ul class="border">
          {% for post in node.posts.all %}
            <li class="index_post"><p>{{ post }}</p></li>

            {% if post.link_text and post.free_videos %}
            <iframe class="youtube_css" src="{{post.link_text}}" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

            {% elif post.link_text and not post.free_videos %}
              <span class="index_post_paid_videos">Видео доступно в платной версии!</span>
            {% endif %}
          {% endfor %}
        </ul>

        
        {% if not node.is_leaf_node %}
          <ul class="children">
            <span class="css-button-text">{{ children }}</span>
          </ul>
        {% endif %}
      </li>
    {% endrecursetree %}
  </ul>

  {% if request.user.is_authenticated %}
    <div class="author_button">
      <a class="css-button-downloads" href="{% url 'index' %}">
        <span class="css-button-text-downloads">Начать обучение</span>
      </a>
    </div>

  {% else %}
    <div class="author_button" id="buy_course">
      <a class="css-button-downloads" href="{% url 'about:author' %}">
        <span class="css-button-text-downloads">Об авторе</span>
      </a>
    </div>

    {% include 'hierarchy/includes/buy_course_button.html' %}
  {% endif %}

</div>
{% endblock %} 

hierarchy/templates/includes/header.html
{% load static %}
<header>
  <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-primary">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'index' %}">
        <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
        <span style="color:#111f6a;">Настя</span>Тейпирование
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse justify-content-end" id="navbarColor01">
        <ul class="navbar-nav">
          {% with request.resolver_match.view_name as view_name %}  
          <li class="nav-item"> 
            <a class="nav-link {% if view_name  == 'about:author' %}active{% endif %}" href="{% url 'about:author' %}">Об авторе</a>
          </li>
          {% endwith %}

          {% if request.user.is_authenticated %}

          {% with request.resolver_match.view_name as view_name %}  
            <li class="nav-item"> 
              <a class="nav-link {% if view_name  == 'index' %}active{% endif %}" href="{% url 'index' %}">Курс</a>
            </li>
          {% endwith %}

          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Пользователь: {{ user.username }}</a>

            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="{% url 'users:password_change' %}">Изменить пароль</a></li>
              <li><hr class="dropdown-divider"></hr></li>
              <li><a class="dropdown-item" href="{% url 'users:logout' %}">Выйти</a></li>
            </ul>
          </li>       

          {% else %}

          {% with request.resolver_match.view_name as view_name %}
            <li class="nav-item"> 
              <a class="nav-link {% if view_name  == 'course_content' %}active{% endif %}" href="{% url 'course_content' %}">Содержание</a>
            </li>
          {% endwith %}
          
          {% with request.resolver_match.view_name as view_name %}  
          <li class="nav-item"> 
            <a class="nav-link link-light {% if view_name  == 'users:login' %}active{% endif %}" href="{% url 'users:login' %}">Войти</a>
          </li>
          {% endwith %}

          {% endif %}
        </ul>

      </div>
    </div>
  </nav>      
</header>

hierarchy/templates/users/logged_out.html
{% extends "hierarchy/base.html" %} 
{% block title %}Вы вышли из системы{% endblock %}
{% block content %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">
        Выход
      </div>
      <div class="card-body">
        <p>
          Вы вышли из своей учётной записи. Ждём вас снова!
        </p>
      </div>
    </div>
  </div>
</div>
{% endblock %}

hierarchy/templates/users/login.html
{% extends "hierarchy/base.html" %} 
{% block title %}Войти{% endblock %}
{% block content %}
{% load user_filters %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Войти на сайт
        </div>
        <div class="card-body">
          {% if form.errors %}
              {% for field in form %}
                {% for error in field.errors %}            
                  <div class="alert alert-danger">
                    {{ error|escape }}
                  </div>
                {% endfor %}
              {% endfor %}
              {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
          {% endif %}

          <form method="post"
            {% if action_url %}
              action="{% url action_url %}"
            {% endif %}
          >
          {% csrf_token %}

          {% for field in form %}
            <div class="form-group row my-3"
              {% if field.field.required %} 
                aria-required="true"
              {% else %}
                aria-required="false"
              {% endif %}
            >
              <label for="{{ field.id_for_label }}">
                {{ field.label }}
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                  {% endif %}
              </label>
              <div>
              {{ field|addclass:'form-control' }}
                {% if field.help_text %}
                  <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                    {{ field.help_text|safe }}
                  </small>
                {% endif %}
              </div>
            </div>
          {% endfor %}
          <div class="col-md-6 offset-md-4">
            <button type="submit" class="btn btn-primary">
              Войти
            </button>
            <a href="{% url 'users:password_reset_form' %}" class="btn btn-link">
              Забыли пароль?
            </a>
          </div>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

hierarchy/templates/users/password_reset_complete.html
{% extends "hierarchy/base.html" %} 
{% block title %}Изменение пароля{% endblock %}
{% block content %}
{% load user_filters %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Восстановление пароля завершено
        </div>
        <div class="card-body">
          <p>Ваш пароль был сохранен. Используйте его для входа</p>
          <a href="{% url 'users:login' %}">войти</a>
        </div>
      </div> 
    </div>
  </div> 
{% endblock %}